Updated deps

diff --git a/common/bin/rofi-bluetooth b/common/bin/rofi-bluetooth
--- a/common/bin/rofi-bluetooth
+++ b/common/bin/rofi-bluetooth
@@ -16,6 +16,15 @@
 # Depends on:
 #   Arch repositories: rofi, bluez-utils (contains bluetoothctl)
 
+if type -p rofi >/dev/null; then
+  echo "Command not found: rofi. Please install it."
+fi
+
+if type -p bluetoothctl >/dev/null; then
+  echo "Command not found: bluetoothctl. Please install bluetoothctl or bluez-utils (contains bluetoothctl)"
+  exit 1
+fi
+
 # Checks if bluetooth controller is powered on
 power_on() {
   if bluetoothctl show | grep -q "Powered: yes"; then
