Updated scripts

diff --git a/scripts/install-dotfiles b/scripts/install-dotfiles
--- a/scripts/install-dotfiles
+++ b/scripts/install-dotfiles
@@ -8,7 +8,7 @@
 ## Options:
 ##     -h, --help                            Help.
 ##     -c, --clear                           Will remove existing dotfiles.
-##         
+##
 ##         --os=OS_NAME                      Operating System. Posible values: common | arch-linux | debian | ...
 ##                                           where common is supposed to work correctly with any linux distro.
 ##                                           `common` is set as default value for this flag.
@@ -37,18 +37,18 @@ wms=${wms:-""}
 [ ! -f "${log_file}" ] && touch "${log_file}"
 
 if [ ! -d "${dotfiles_dir}" ] || [ -n "${clear}" ]; then
-    describe "Removing existing dotfiles"
+  describe "Removing existing dotfiles"
 
-    # Delete existing dotfiles and folders
-    rm -rf "${dotfiles_dir}" > /dev/null 2>&1
+  # Delete existing dotfiles and folders
+  rm -rf "${dotfiles_dir}" >/dev/null 2>&1
 
-    # Create dotfiles folder
-    mkdir "${dotfiles_dir}"
-    mkdir "${dotfiles_dir}"/config
+  # Create dotfiles folder
+  mkdir "${dotfiles_dir}"
+  mkdir "${dotfiles_dir}"/config
 
-    mkdir "${dotfiles_dir}"/custom-config
+  mkdir "${dotfiles_dir}"/custom-config
 
-    log_success "Success" "${config}" "${log_file}"
+  log_success "Success" "${config}" "${log_file}"
 fi
 
 #==========================================
@@ -58,19 +58,19 @@ describe "Installing binaries\n" 0
 cp -rf "${ROOT}"/../common/bin "${dotfiles_dir}"
 
 if [ -d "${ROOT}/../${os}/bin" ]; then
-    cp -rf "${ROOT}"/../${os}/bin "${dotfiles_dir}"
+  cp -rf "${ROOT}"/../"${os}"/bin "${dotfiles_dir}"
 fi
 
 if [ ! -d "${HOME}/bin" ]; then
-    mkdir ~/bin
+  mkdir ~/bin
 fi
 
 for bin_path in $(find "${dotfiles_dir}"/bin -maxdepth 1 -mindepth 1 -type f); do
-    bin=$(basename "${bin_path}")
+  bin=$(basename "${bin_path}")
 
-    chmod +x "${bin_path}"
-    sudo rm -rf ~/bin/"${bin}" > /dev/null 2>&1
-    ln -sf "${bin_path}" ~/bin/"${bin}"
+  chmod +x "${bin_path}"
+  sudo rm -rf ~/bin/"${bin}" >/dev/null 2>&1
+  ln -sf "${bin_path}" ~/bin/"${bin}"
 done
 
 echo
@@ -84,41 +84,41 @@ failed=0
 
 describe "Installing dotfiles\n" 0
 for config_path in $(find "${ROOT}"/../common/config/ -maxdepth 1 -mindepth 1 -type d); do
-    config=$(basename "${config_path}")
+  config=$(basename "${config_path}")
 
-    describe "Installing ${config} dotfiles"
+  describe "Installing ${config} dotfiles"
 
-    os_config_path=${config_path}
+  os_config_path=${config_path}
 
-    if [ -x "${ROOT}/../${os}/config/${config}/install" ]; then
-        os_config_path="${ROOT}/../${os}/config/${config}"
-    fi
+  if [ -x "${ROOT}/../${os}/config/${config}/install" ]; then
+    os_config_path="${ROOT}/../${os}/config/${config}"
+  fi
 
-    cp -rf "${os_config_path}" "${dotfiles_dir}"/config
-    if bash "${dotfiles_dir}"/config/"${config}"/install; then
-        log_success "Installed successfully" "${config}" "${log_file}"
-        ((success+=1))
-    else
-        log_failed "Installation failed" "${config}" "${log_file}"
-        ((failed+=1))
-    fi
+  cp -rf "${os_config_path}" "${dotfiles_dir}"/config
+  if bash "${dotfiles_dir}"/config/"${config}"/install; then
+    log_success "Installed successfully" "${config}" "${log_file}"
+    ((success += 1))
+  else
+    log_failed "Installation failed" "${config}" "${log_file}"
+    ((failed += 1))
+  fi
 done
 
-all=$(( ${success} + ${failed} ))
+all=$((${success} + ${failed}))
 
 echo
 echo "${GREEN}Success: ${success} ${RED}Failed: ${failed}${RESET} Total: ${all}"
 
 describe "Setting up default and custom configs\n\n"
 
-rm -rf "${dotfiles_dir}"/default-config > /dev/null 2>&1
+rm -rf "${dotfiles_dir}"/default-config >/dev/null 2>&1
 cp -rf "${ROOT}"/../default-config/common "${dotfiles_dir}"/default-config
 
 for wm in xfce4 $(echo "${wms}" | tr ',' '\n'); do
-    [ -e "${ROOT}/../default-config/wm/${wm}/install" ] || continue
-    cp -rf "${ROOT}"/../default-config/wm/"${wm}" "${dotfiles_dir}"/default-config
-    cp -rf "${ROOT}"/../default-config/wm/"${wm}" "${dotfiles_dir}"/custom-config
-    chmod +x "${dotfiles_dir}"/default-config/"${wm}"/install
+  [ -e "${ROOT}/../default-config/wm/${wm}/install" ] || continue
+  cp -rf "${ROOT}"/../default-config/wm/"${wm}" "${dotfiles_dir}"/default-config
+  cp -rf "${ROOT}"/../default-config/wm/"${wm}" "${dotfiles_dir}"/custom-config
+  chmod +x "${dotfiles_dir}"/default-config/"${wm}"/install
 done
 
 chmod +x "${dotfiles_dir}"/default-config/install
diff --git a/scripts/install-pkgs b/scripts/install-pkgs
--- a/scripts/install-pkgs
+++ b/scripts/install-pkgs
@@ -39,37 +39,37 @@ pkgs=${pkgs:-""}
 #==========================================
 # Installing process
 #==========================================
-describe "Starting process\n\n" 0 
+describe "Starting process\n\n" 0
 
 success=0
 failed=0
 
 for pkg in $(echo "${pkgs}" | tr ',' '\n'); do
-    describe "Fetching ${pkg}"
-    if type -p "${pkg}" > /dev/null && [ -n "$upgrade" ]; then
-        log_success "Already installed" "${pkg}" "${log_file}"
-        ((success+=1))
+  describe "Fetching ${pkg}"
+  if type -p "${pkg}" >/dev/null && [ -n "$upgrade" ]; then
+    log_success "Already installed" "${pkg}" "${log_file}"
+    ((success += 1))
+  else
+    if ! pkg_exists "${pkg}"; then
+      log_failed "Package not found" "${pkg}" "${log_file}"
+      ((failed += 1))
+      continue
+    fi
+
+    log_warn "Package not installed" "${pkg}" "${log_file}"
+
+    describe "Installing ${pkg}\n" 0
+    if pkg_install "${pkg}"; then
+      log_success "Installed successfully" "${pkg}" "${log_file}"
+      ((success += 1))
     else
-        if ! pkg_exists "${pkg}"; then
-            log_failed "Package not found" "${pkg}" "${log_file}"
-            ((failed+=1))
-            continue
-        fi
-
-        log_warn "Package not installed" "${pkg}" "${log_file}"
-
-        describe "Installing ${pkg}\n" 0
-        if pkg_install "${pkg}"; then
-            log_success "Installed successfully" "${pkg}" "${log_file}"
-            ((success+=1))
-        else
-            log_failed "Installation fialed" "${pkg}" "${log_file}"
-            ((failed+=1))
-        fi   
-    fi   
+      log_failed "Installation fialed" "${pkg}" "${log_file}"
+      ((failed += 1))
+    fi
+  fi
 done
 
-all=$(( ${success} + ${failed} ))
+all=$((success + failed))
 
 echo
 echo "${GREEN}Success: ${success} ${RED}Failed: ${failed}${REET} Total: ${all}"
